# Generated by Django 4.1.1 on 2022-10-21 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ebilling", "0004_alter_company_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=100)),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="getPermissions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
