# Generated by Django 4.1.1 on 2022-10-21 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ebilling", "0005_userpermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpermission",
            name="user",
            field=models.ManyToManyField(
                blank=True, related_name="getPermissions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
