# Generated by Django 4.1.1 on 2022-10-21 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ebilling", "0006_alter_userpermission_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ebilling.company",
            ),
        ),
    ]
