# Generated by Django 4.1.1 on 2022-10-21 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ebilling", "0007_history_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ebilling.company"
            ),
        ),
    ]
